<?php require_once './templates/layout/header.phtml'?>
<h2> <?= $car->marca ?></h2>
<h3> <?= $car->modelo ?></h3>
<h3> <?= $car->precio ?></h3>
<ul>
    <li><?= $car->año ?></li>
    <li><?= $car->puertas ?></li>
    <li><?= $car->hp ?></li>
    <li><?= $car->categoria ?></li>
    
</ul>
<form action="<?= BASE_URL ?>update/<?= $car->id?>" method="POST">
    <label for="brand">Marca </label>
    <input type="text" name="brand" id="" required>
    <label for="model">Modelo </label>
    <input type="text" name="model" id="" required >
    <label for="categories">Categoria </label>
    <input type="text" name="categories" id="" required>
    <label for="year">Año </label>
    <input type="number" name="year" id="" required>
    <label for="doors">Puertas </label>
    <input type="number" name="doors" id="" required>
    <label for="power">HP </label>
    <input type="number" name="power" id="" required>
    <label for="ditribuitor">Distribuidor </label>
    <select name="distribuitor" id=""></select>
    <label for="car-price">Precio </label>
    <input type="number" name="car-price" id="" required>
    <button type="submit">Aceptar</button>
</form>
<?php require_once './templates/layout/footer.phtml'?>