<?php require_once './templates/layout/header.phtml'; ?>
<div class="card">
    <div class="home-button">
        <a href="<?=BASE_URL?>vehicles/list">
            <div class="card-image">
                <img src="<?= BASE_URL?>/css/images/sleek-front-facing-red-sports-car-vector-modern-graphic-symbol_1105246-373.png" alt="">
            </div>
            <div class="card-text">
                <p>Vehiculos</p>
            </div>
        </a>
    </div>
</div>
<div class="card">
    <div class="home-button">
        <a href="<?=BASE_URL?>distributors/list">
            <div class="card-image">
                <img src="<?= BASE_URL?>/css/images/sleek-front-facing-red-sports-car-vector-modern-graphic-symbol_1105246-373333.png" alt="">
            </div>
            <div class="card-text">
                <p>Distribuidores</p>
            </div>
        </a>
    </div>
</div>
<?php require_once './templates/layout/footer.phtml'; ?>
