<?php require_once './templates/layout/header.phtml'?>

<div class="form-container">
    <?php if($error) :?>
        <div class="error">
            <h3> <?= $error ?> </h3>
        </div>
    <?php endif ?>
    <form action="login" method="POST">
        <label for="username"> Usuario </label>
        <input type="text" name="username" id="" required>
        <label for="password"> Contraseña </label>
        <input type="password" name="password" id="" required>
        <button type="submit">Iniciar Sesion</button>
    </form>
</div>
<?php require_once './templates/layout/footer.phtml'?>