<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>M&L Concesionaria</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cantarell:ital,wght@0,400;0,700;1,400;1,700&family=Sora:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="shortcut icon" href="./css/favicon.svg" type="image/x-icon">
</head>
<body>
    <header>
        <h1 class="main-title">Concesionaria</h1>

        <nav>
            <div class="nav-bar">
                <div>
                    <ul>
                        <li> <a href=<?= BASE_URL ?>>inicio</a></li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <?php if(!$this->user):?>
                        <li><a href= <?= BASE_URL . 'log' ?>>Iniciar sesion</a></li>
                        <?php endif;?>
                        <?php if($this->user):?>
                        <li> <?php $this->user->usuario ?></li>
                        <li><a href= <?= BASE_URL . 'logout' ?>>Cerrar sesion</a></li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
        </nav>
        
    </header>
    
    <main>