<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>M&L Concesionaria</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cantarell:ital,wght@0,400;0,700;1,400;1,700&family=Sora:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<?= BASE_URL ?>/css/style.css">
    <link rel="shortcut icon" href="<?= BASE_URL ?>/css/favicon.svg" type="image/x-icon">
</head>
<body>
    <header class="header">
        <h1 class="main-title">Concesionaria</h1>
        <nav>
            <div class="nav-bar">
                <div>
                    <ul>
                        <li> <div class="interactive"><a href=<?= BASE_URL ?>>inicio</a></div></li>
                    </ul>
                </div>
                <div>
                    
                        <?php if($this->user && $this->user->rol == 'none'):?>
                        <div class="login-button"><a href= "<?= BASE_URL . 'log' ?>">Iniciar sesion</a></div>
                        <?php endif ?>

                        <?php if($this->user && $this->user->rol == 'admin'):?>
                        <p>👤 <?= $this->user->usuario ?></p>
                        <div class="login-button"><a href= "<?= BASE_URL . 'logout' ?>" >Cerrar sesion</a></div>
                        <?php endif ?>
                </div>
            </div>
        </nav>
        
    </header>
    
    <main>
        <div class="main-body">